# Generated by Django 5.2.1 on 2025-05-09 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testing_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PrivateItem',
            new_name='Item',
        ),
    ]
